# NumPy Practice Notebook

This notebook contains a series of practice problems to help you understand and apply core concepts in NumPy.

---

## 🧩 1. Array Creation
**Question:** Create the following arrays using NumPy:
1. A 1D array with numbers from 0 to 9
2. A 2D array of shape (3, 3) filled with zeros
3. A 2D array of shape (2, 4) filled with ones
4. A 3x3 identity matrix


---


In [4]:
import numpy as np

In [1]:
x1=[0,1,2,3]
x2=[[0,0,0],[0,0,0],[0,0,0]]
x3=[[1,1,1,1],[1,1,1,1]]
x4=[[1,0,0],[0,1,0],[0,0,1]]



## 🧪 2. Array Inspection
**Question:** Given a NumPy array `arr`, print:
1. Its shape
2. Its data type
3. The number of dimensions
4. The total number of elements

```python
arr = np.array([[1, 2, 3], [4, 5, 6]])

```

---


In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(arr.size)

(2, 3)
int64
2
6



## 🔍 3. Indexing and Slicing
**Question:** Using the array below, do the following:
1. Slice the first two rows
2. Get the last column
3. Extract the element in the second row and third column
4. Reverse the rows

```python
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

```


In [8]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[:2])
print(arr[:,2])
print(arr[1,2])
print(arr[::-1])

[[10 20 30]
 [40 50 60]]
[30 60 90]
60
[[70 80 90]
 [40 50 60]
 [10 20 30]]



---

## 🔁 4. More Slicing Practice
**Question:**
Given the array below, extract:
1. All even numbers
2. The second and third rows
3. The last two columns
4. A subarray containing the middle 2x2 block

```python
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

```


In [9]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])
print(arr[arr%2==0])
print(arr[1:3])
print(arr[:,2:])
print(arr[1:3,1:3])

[ 2  4  6  8 10 12 14 16]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]
[[ 6  7]
 [10 11]]



---

## ➕ 5. Arithmetic Operations
**Question:** Perform the following using NumPy arrays:
1. Add two arrays element-wise
2. Multiply two arrays element-wise
3. Raise all elements of an array to the power of 2

```python
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

```

---


In [14]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
np.addition=arr1+arr2
print(addition)
multiply_result = arr1 * arr2
print(multiply_result)
power_result = arr1 ** 2
print(power_result)

[5 7 9]
[ 4 10 18]
[1 4 9]



## 📏 6. Broadcasting
**Question:** Use broadcasting to:
1. Add a 1D array to each row of a 2D array
2. Multiply each row of a 2D array by a 1D array
3. Subtract a scalar from each element in an array
4. Add a column vector to each column of a matrix

```python
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])
C = np.array([[1], [2]])

```


In [ ]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([10, 20, 30])
C = np.array([[1], [2]])


---

## 🔁 7. More Broadcasting Practice
**Question:** Try these:
1. Add a 1D array of shape (4,) to a 2D array of shape (3,4)
2. Multiply a (3,1) column array to a (1,4) row array and observe the shape
3. Add a scalar to the entire array

```python
A = np.arange(12).reshape(3, 4)
B = np.array([100, 200, 300, 400])
C = np.array([[2], [3], [4]])

```


In [15]:

A = np.arange(12).reshape(3, 4)
B = np.array([100, 200, 300, 400])
C = np.array([[2], [3], [4]])

add_result = A + B
multiply_result = C * B.reshape(1, 4)
scalar_result = A + 10

print("1. A + B:\n", add_result)
print("2. C * B.reshape(1, 4):\n", multiply_result)
print("3. A + 10:\n", scalar_result)

1. A + B:
 [[100 201 302 403]
 [104 205 306 407]
 [108 209 310 411]]
2. C * B.reshape(1, 4):
 [[ 200  400  600  800]
 [ 300  600  900 1200]
 [ 400  800 1200 1600]]
3. A + 10:
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]



---

## 🔃 8. Reshaping and Flattening
**Question:**
1. Reshape a 1D array of 12 elements into a 3x4 matrix
2. Flatten a 2D array into a 1D array

```python
arr = np.arange(12)

```


In [16]:

arr = np.arange(12)
reshaped_arr = arr.reshape(3, 4)
flattened_arr = reshaped_arr.flatten()

print("Reshaped array:\n", reshaped_arr)
print("Flattened array:\n", flattened_arr)

Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]



---

## 🔗 9. Stacking and Splitting
**Question:** Stack and split arrays:
1. Stack two (2, 2) arrays vertically and horizontally
2. reshape a (4, 4) array into array of shape (2, 8)


---



## 🧠 10. Boolean Masking
**Question:**
Given an array:
1. Select all elements > 10
2. Replace all even numbers with -1

```python
arr = np.array([[5, 10, 15], [20, 25, 30]])

```


In [21]:

arr = np.array([[5, 10, 15], [20, 25, 30]])

greater_than_10 = arr[arr > 10]
arr[arr % 2 == 0] = -1
print(arr)

[[ 5 -1 15]
 [-1 25 -1]]



---

## 🧮 11. Aggregation
**Question:** Calculate:
1. Sum of all elements
2. Mean of each column
3. Max value in each row
4. Standard deviation of the array

```python
arr = np.array([[1, 2, 3], [4, 5, 6]])

```


In [24]:

arr = np.array([[1, 2, 3], [4, 5, 6]])

total_sum = np.sum(arr)
column_mean = np.mean(arr, axis=0)
row_max = np.max(arr, axis=1)
std_dev = np.std(arr)
print(total_sum)
print(column_mean)
print(row_max)
print(std_dev)

21
[2.5 3.5 4.5]
[3 6]
1.707825127659933



---

## 🧲 12. Dot Product and Matrix Multiplication
**Question:**
1. Multiply two matrices using `np.dot`

```python
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

```


In [26]:

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

result = np.dot(A,B)
print(result)

[[19 22]
 [43 50]]



---

## 🔢 13. Random Numbers
**Question:**
1. Generate a 2x3 array of random numbers between 0 and 1
2. Generate 10 random integers between 50 and 100



In [33]:
arr = np.random.uniform(low=0, high=1, size=(2,3))
x=np.random.uniform(low=50,high=100,size=10)

SyntaxError: invalid syntax (ipython-input-721040890.py, line 3)


---

## 📐 14. Linear Algebra
**Question:**
1. Find the rank of a matrix
2. Compute the inverse of a matrix
3. Compute the determinant of a matrix



---


In [34]:

A = np.array([[1, 2], [3, 4]])

rank = np.linalg.matrix_rank(A)
inverse = np.linalg.inv(A)
determinant = np.linalg.det(A)

print("Rank:", rank)
print("Inverse:\n", inverse)
print("Determinant:", determinant)

Rank: 2
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant: -2.0000000000000004



## ⭐ Bonus Challenge
**Question:**
Given a 2D array of shape (6, 6), extract all 3x3 submatrices (using slicing) and store them in a list.




---

Happy coding! 🎯
